spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    schema: classpath:h2/schema.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

mybatis:
  mapper-locations: classpath:h2/mapper/*.xml
  type-aliases-package: org.conway.dockertest.domwain