server:
    port: 10100

mybatis:
    type-aliases-package: org.conway.dockertest.domain
    configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
    level:
        root: DEBUG
        org.conway.dockertest: DEBUG

springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        operations-sorter: method

management:
    endpoint:
        httptrace:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
                exclude: shutdown
